### ISSUE TITLE
Bug in the Debug. Incomplete files with ISOFIT_DEBUG=1 and analytical_line

### ISSUE THREAD

**Issue by evan-greenbrg** [isofit/isofit#555] opened 2024-10-10 23:27 UTC
Possible small issue. I was working with the ISOFIT_DEBUG=1 flag running through the analytical line. My runs kept generating incomplete files (image included here). It looks like the workers run through only 1 row and then exit. The number of lines included in the file equal the number of workers allocated.

<img width="436" alt="Screenshot 2024-10-10 at 4 23 08 PM" src="https://github.com/user-attachments/assets/2e91cfef-32c8-4f1b-bbba-7a2ff2f98f3a">

I just ran the following cli command and reproduced the issue. The $vars are local paths:
`isofit apply_oe $rdn $loc $obs $rfl emit --analytical_line --surface_path $surface --emulator_base $emulator --num_neighbors 20`

**Comment by jammont** [comment] 2024-10-11 16:43
Duplicate of #549, but with more context so leaving it up

Will be addressed soon

**Closed** 2024-10-17 16:08 UTC
Labels: bugfix
